version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "5029:8080"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: collaborative_editing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  db-data:
